sudo: required

language: bash

services:
  - docker

script:
- docker build -t zhengcan/clearsilver .
- docker build -t zhengcan/clearsilver-test .
- docker run --rm -w "/root/test" zhengcan/clearsilver-test "python2 hello.py"

after_script:
- docker images
