sudo: required

language: bash

services:
  - docker

script:
- docker build -t zhengcan/clearsilver .
- docker run -v `pwd`/src:/root/src --rm -w /root/src zhengcan/clearsilver python2 hello.py

after_script:
- docker images
