sudo: required

language: bash

services:
  - docker

script:
- docker build -t canzheng/clearsilver .
- docker run -v test:/root/test --rm canzheng/clearsilver cd /root/test; python2 hello.py

after_script:
- docker images
